# Gradle - Comment test
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


pool:
  vmImage: 'windows-latest'


steps:

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx12288m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean toolsApiTests --rerun-tasks --stacktrace --continue --info --debug'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'Extent-Reports'
    PathToPublish: './target/Extent-Reports/'