# Gradle - Comment test
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


pool:
  vmImage: 'windows-latest'

steps:

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx12288m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean toolsApiTests --rerun-tasks --stacktrace --continue --info --debug'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'Extent-Reports'
    PathToPublish: './target/Extent-Reports/'

- task: EmailReport@1
  inputs:
    sendMailConditionConfig: 'Always'
    subject: '[{environmentStatus}] {passPercentage} tests passed in $(Release.EnvironmentName) stage for $(Build.BuildNumber)'
    toAddress: 'gaurav.jain@infostride.com'
    includeInCcSectionStr: '1'
    ccAddress: 'gulshan.kumar@infostride.com'
    defaultDomain: 'microsoft.com'
    groupTestResultsBy: 'run'
    includeCommits: true
    maxTestFailuresToShow: '15'
    includeOthersInTotal: true
    usePreviousEnvironment: false
    smtpConnectionEndpoint: 'INFOSMTP'